galaxy_info:

  author: 'Ricardo Gameiro'
  description: 'Setup a basic NGINX server with a default website (redirects all HTPP to HTTPS).'

  license: 'MIT'

  min_ansible_version: '2.1'

  galaxy_tags: []

dependencies:
  - role: 'firewall'
