---

config:
  general:
    service_port_delta: 0
    service_port_step: 5
    rust_port_delta: 100
    rust_port_step: 5
  develop:
    bind_start_port: 3200
    log_level: 'debug'
  stage:
    bind_start_port: 3400
    log_level: 'info'
  release:
    bind_start_port: 3600
    log_level: 'info'
